// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pikoci/pikoci/pikoci/apitoken (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/apitoken_repository.go -mock_names=Repository=ApiTokenRepository -package mock github.com/pikoci/pikoci/pikoci/apitoken Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	apitoken "github.com/pikoci/pikoci/pikoci/apitoken"
	gomock "go.uber.org/mock/gomock"
)

// ApiTokenRepository is a mock of Repository interface.
type ApiTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *ApiTokenRepositoryMockRecorder
	isgomock struct{}
}

// ApiTokenRepositoryMockRecorder is the mock recorder for ApiTokenRepository.
type ApiTokenRepositoryMockRecorder struct {
	mock *ApiTokenRepository
}

// NewApiTokenRepository creates a new mock instance.
func NewApiTokenRepository(ctrl *gomock.Controller) *ApiTokenRepository {
	mock := &ApiTokenRepository{ctrl: ctrl}
	mock.recorder = &ApiTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ApiTokenRepository) EXPECT() *ApiTokenRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *ApiTokenRepository) Create(ctx context.Context, t apitoken.Token, tokenHash string) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, t, tokenHash)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *ApiTokenRepositoryMockRecorder) Create(ctx, t, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*ApiTokenRepository)(nil).Create), ctx, t, tokenHash)
}

// Delete mocks base method.
func (m *ApiTokenRepository) Delete(ctx context.Context, username string, tokenID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, username, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *ApiTokenRepositoryMockRecorder) Delete(ctx, username, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*ApiTokenRepository)(nil).Delete), ctx, username, tokenID)
}

// DeleteByTeamMember mocks base method.
func (m *ApiTokenRepository) DeleteByTeamMember(ctx context.Context, username, teamCanonical string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByTeamMember", ctx, username, teamCanonical)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByTeamMember indicates an expected call of DeleteByTeamMember.
func (mr *ApiTokenRepositoryMockRecorder) DeleteByTeamMember(ctx, username, teamCanonical any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByTeamMember", reflect.TypeOf((*ApiTokenRepository)(nil).DeleteByTeamMember), ctx, username, teamCanonical)
}

// Filter mocks base method.
func (m *ApiTokenRepository) Filter(ctx context.Context, username string) ([]*apitoken.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, username)
	ret0, _ := ret[0].([]*apitoken.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *ApiTokenRepositoryMockRecorder) Filter(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*ApiTokenRepository)(nil).Filter), ctx, username)
}

// FindByHash mocks base method.
func (m *ApiTokenRepository) FindByHash(ctx context.Context, tokenHash string) (*apitoken.AuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHash", ctx, tokenHash)
	ret0, _ := ret[0].(*apitoken.AuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHash indicates an expected call of FindByHash.
func (mr *ApiTokenRepositoryMockRecorder) FindByHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHash", reflect.TypeOf((*ApiTokenRepository)(nil).FindByHash), ctx, tokenHash)
}

// UpdateLastUsed mocks base method.
func (m *ApiTokenRepository) UpdateLastUsed(ctx context.Context, tokenID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastUsed", ctx, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastUsed indicates an expected call of UpdateLastUsed.
func (mr *ApiTokenRepositoryMockRecorder) UpdateLastUsed(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastUsed", reflect.TypeOf((*ApiTokenRepository)(nil).UpdateLastUsed), ctx, tokenID)
}
