// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pikoci/pikoci/pikoci/auditlog (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/auditlog_repository.go -mock_names=Repository=AuditLogRepository -package mock github.com/pikoci/pikoci/pikoci/auditlog Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	auditlog "github.com/pikoci/pikoci/pikoci/auditlog"
	gomock "go.uber.org/mock/gomock"
)

// AuditLogRepository is a mock of Repository interface.
type AuditLogRepository struct {
	ctrl     *gomock.Controller
	recorder *AuditLogRepositoryMockRecorder
	isgomock struct{}
}

// AuditLogRepositoryMockRecorder is the mock recorder for AuditLogRepository.
type AuditLogRepositoryMockRecorder struct {
	mock *AuditLogRepository
}

// NewAuditLogRepository creates a new mock instance.
func NewAuditLogRepository(ctrl *gomock.Controller) *AuditLogRepository {
	mock := &AuditLogRepository{ctrl: ctrl}
	mock.recorder = &AuditLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *AuditLogRepository) EXPECT() *AuditLogRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *AuditLogRepository) Create(ctx context.Context, teamCanonical string, e auditlog.Entry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, teamCanonical, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *AuditLogRepositoryMockRecorder) Create(ctx, teamCanonical, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*AuditLogRepository)(nil).Create), ctx, teamCanonical, e)
}

// Filter mocks base method.
func (m *AuditLogRepository) Filter(ctx context.Context, teamCanonical string, opts auditlog.FilterOpts) ([]*auditlog.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, teamCanonical, opts)
	ret0, _ := ret[0].([]*auditlog.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *AuditLogRepositoryMockRecorder) Filter(ctx, teamCanonical, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*AuditLogRepository)(nil).Filter), ctx, teamCanonical, opts)
}
