// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pikoci/pikoci/pikoci/job (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/job_repository.go -mock_names=Repository=JobRepository -package mock github.com/pikoci/pikoci/pikoci/job Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	job "github.com/pikoci/pikoci/pikoci/job"
	gomock "go.uber.org/mock/gomock"
)

// JobRepository is a mock of Repository interface.
type JobRepository struct {
	ctrl     *gomock.Controller
	recorder *JobRepositoryMockRecorder
	isgomock struct{}
}

// JobRepositoryMockRecorder is the mock recorder for JobRepository.
type JobRepositoryMockRecorder struct {
	mock *JobRepository
}

// NewJobRepository creates a new mock instance.
func NewJobRepository(ctrl *gomock.Controller) *JobRepository {
	mock := &JobRepository{ctrl: ctrl}
	mock.recorder = &JobRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *JobRepository) EXPECT() *JobRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *JobRepository) Create(ctx context.Context, tc, pn string, j job.Job) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tc, pn, j)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *JobRepositoryMockRecorder) Create(ctx, tc, pn, j any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*JobRepository)(nil).Create), ctx, tc, pn, j)
}

// Delete mocks base method.
func (m *JobRepository) Delete(ctx context.Context, tc, pn, jn string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tc, pn, jn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *JobRepositoryMockRecorder) Delete(ctx, tc, pn, jn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*JobRepository)(nil).Delete), ctx, tc, pn, jn)
}

// Filter mocks base method.
func (m *JobRepository) Filter(ctx context.Context, tc, pn string) ([]*job.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, tc, pn)
	ret0, _ := ret[0].([]*job.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *JobRepositoryMockRecorder) Filter(ctx, tc, pn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*JobRepository)(nil).Filter), ctx, tc, pn)
}

// FilterByForEachGroup mocks base method.
func (m *JobRepository) FilterByForEachGroup(ctx context.Context, tc, pn, group string) ([]*job.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterByForEachGroup", ctx, tc, pn, group)
	ret0, _ := ret[0].([]*job.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterByForEachGroup indicates an expected call of FilterByForEachGroup.
func (mr *JobRepositoryMockRecorder) FilterByForEachGroup(ctx, tc, pn, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterByForEachGroup", reflect.TypeOf((*JobRepository)(nil).FilterByForEachGroup), ctx, tc, pn, group)
}

// Find mocks base method.
func (m *JobRepository) Find(ctx context.Context, tc, pn, jn string) (*job.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, tc, pn, jn)
	ret0, _ := ret[0].(*job.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *JobRepositoryMockRecorder) Find(ctx, tc, pn, jn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*JobRepository)(nil).Find), ctx, tc, pn, jn)
}

// FindJobsBySerialGroups mocks base method.
func (m *JobRepository) FindJobsBySerialGroups(ctx context.Context, tc, pn string, serialGroups []string) ([]*job.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindJobsBySerialGroups", ctx, tc, pn, serialGroups)
	ret0, _ := ret[0].([]*job.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindJobsBySerialGroups indicates an expected call of FindJobsBySerialGroups.
func (mr *JobRepositoryMockRecorder) FindJobsBySerialGroups(ctx, tc, pn, serialGroups any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindJobsBySerialGroups", reflect.TypeOf((*JobRepository)(nil).FindJobsBySerialGroups), ctx, tc, pn, serialGroups)
}

// PauseAll mocks base method.
func (m *JobRepository) PauseAll(ctx context.Context, tc, pn string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseAll", ctx, tc, pn)
	ret0, _ := ret[0].(error)
	return ret0
}

// PauseAll indicates an expected call of PauseAll.
func (mr *JobRepositoryMockRecorder) PauseAll(ctx, tc, pn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseAll", reflect.TypeOf((*JobRepository)(nil).PauseAll), ctx, tc, pn)
}

// SetPaused mocks base method.
func (m *JobRepository) SetPaused(ctx context.Context, tc, pn, jn string, paused bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPaused", ctx, tc, pn, jn, paused)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPaused indicates an expected call of SetPaused.
func (mr *JobRepositoryMockRecorder) SetPaused(ctx, tc, pn, jn, paused any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPaused", reflect.TypeOf((*JobRepository)(nil).SetPaused), ctx, tc, pn, jn, paused)
}

// UnpauseAll mocks base method.
func (m *JobRepository) UnpauseAll(ctx context.Context, tc, pn string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpauseAll", ctx, tc, pn)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnpauseAll indicates an expected call of UnpauseAll.
func (mr *JobRepositoryMockRecorder) UnpauseAll(ctx, tc, pn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpauseAll", reflect.TypeOf((*JobRepository)(nil).UnpauseAll), ctx, tc, pn)
}

// Update mocks base method.
func (m *JobRepository) Update(ctx context.Context, tc, pn, jn string, j job.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tc, pn, jn, j)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *JobRepositoryMockRecorder) Update(ctx, tc, pn, jn, j any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*JobRepository)(nil).Update), ctx, tc, pn, jn, j)
}
