// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pikoci/pikoci/pikoci/notiftype (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/notification_type_repository.go -mock_names=Repository=NotificationTypeRepository -package mock github.com/pikoci/pikoci/pikoci/notiftype Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	notiftype "github.com/pikoci/pikoci/pikoci/notiftype"
	gomock "go.uber.org/mock/gomock"
)

// NotificationTypeRepository is a mock of Repository interface.
type NotificationTypeRepository struct {
	ctrl     *gomock.Controller
	recorder *NotificationTypeRepositoryMockRecorder
	isgomock struct{}
}

// NotificationTypeRepositoryMockRecorder is the mock recorder for NotificationTypeRepository.
type NotificationTypeRepositoryMockRecorder struct {
	mock *NotificationTypeRepository
}

// NewNotificationTypeRepository creates a new mock instance.
func NewNotificationTypeRepository(ctrl *gomock.Controller) *NotificationTypeRepository {
	mock := &NotificationTypeRepository{ctrl: ctrl}
	mock.recorder = &NotificationTypeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *NotificationTypeRepository) EXPECT() *NotificationTypeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *NotificationTypeRepository) Create(ctx context.Context, tc, pn string, nt notiftype.NotificationType) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tc, pn, nt)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *NotificationTypeRepositoryMockRecorder) Create(ctx, tc, pn, nt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*NotificationTypeRepository)(nil).Create), ctx, tc, pn, nt)
}

// Delete mocks base method.
func (m *NotificationTypeRepository) Delete(ctx context.Context, tc, pn, tn string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tc, pn, tn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *NotificationTypeRepositoryMockRecorder) Delete(ctx, tc, pn, tn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*NotificationTypeRepository)(nil).Delete), ctx, tc, pn, tn)
}

// Filter mocks base method.
func (m *NotificationTypeRepository) Filter(ctx context.Context, tc, pn string) ([]*notiftype.NotificationType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, tc, pn)
	ret0, _ := ret[0].([]*notiftype.NotificationType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *NotificationTypeRepositoryMockRecorder) Filter(ctx, tc, pn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*NotificationTypeRepository)(nil).Filter), ctx, tc, pn)
}

// Find mocks base method.
func (m *NotificationTypeRepository) Find(ctx context.Context, tc, pn, tn string) (*notiftype.NotificationType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, tc, pn, tn)
	ret0, _ := ret[0].(*notiftype.NotificationType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *NotificationTypeRepositoryMockRecorder) Find(ctx, tc, pn, tn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*NotificationTypeRepository)(nil).Find), ctx, tc, pn, tn)
}

// Update mocks base method.
func (m *NotificationTypeRepository) Update(ctx context.Context, tc, pn, tn string, nt notiftype.NotificationType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tc, pn, tn, nt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *NotificationTypeRepositoryMockRecorder) Update(ctx, tc, pn, tn, nt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*NotificationTypeRepository)(nil).Update), ctx, tc, pn, tn, nt)
}
