// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pikoci/pikoci/pikoci/notification (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/notification_repository.go -mock_names=Repository=NotificationRepository -package mock github.com/pikoci/pikoci/pikoci/notification Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	notification "github.com/pikoci/pikoci/pikoci/notification"
	gomock "go.uber.org/mock/gomock"
)

// NotificationRepository is a mock of Repository interface.
type NotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *NotificationRepositoryMockRecorder
	isgomock struct{}
}

// NotificationRepositoryMockRecorder is the mock recorder for NotificationRepository.
type NotificationRepositoryMockRecorder struct {
	mock *NotificationRepository
}

// NewNotificationRepository creates a new mock instance.
func NewNotificationRepository(ctrl *gomock.Controller) *NotificationRepository {
	mock := &NotificationRepository{ctrl: ctrl}
	mock.recorder = &NotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *NotificationRepository) EXPECT() *NotificationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *NotificationRepository) Create(ctx context.Context, tc, pn string, n notification.Notification) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tc, pn, n)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *NotificationRepositoryMockRecorder) Create(ctx, tc, pn, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*NotificationRepository)(nil).Create), ctx, tc, pn, n)
}

// Delete mocks base method.
func (m *NotificationRepository) Delete(ctx context.Context, tc, pn, nCan string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tc, pn, nCan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *NotificationRepositoryMockRecorder) Delete(ctx, tc, pn, nCan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*NotificationRepository)(nil).Delete), ctx, tc, pn, nCan)
}

// Filter mocks base method.
func (m *NotificationRepository) Filter(ctx context.Context, tc, pn string) ([]*notification.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, tc, pn)
	ret0, _ := ret[0].([]*notification.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *NotificationRepositoryMockRecorder) Filter(ctx, tc, pn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*NotificationRepository)(nil).Filter), ctx, tc, pn)
}

// Find mocks base method.
func (m *NotificationRepository) Find(ctx context.Context, tc, pn, nCan string) (*notification.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, tc, pn, nCan)
	ret0, _ := ret[0].(*notification.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *NotificationRepositoryMockRecorder) Find(ctx, tc, pn, nCan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*NotificationRepository)(nil).Find), ctx, tc, pn, nCan)
}

// Update mocks base method.
func (m *NotificationRepository) Update(ctx context.Context, tc, pn, nCan string, n notification.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tc, pn, nCan, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *NotificationRepositoryMockRecorder) Update(ctx, tc, pn, nCan, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*NotificationRepository)(nil).Update), ctx, tc, pn, nCan, n)
}
