// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pikoci/pikoci/pikoci/oauthprovider (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/oauth_provider_repository.go -mock_names=Repository=OAuthProviderRepository -package mock github.com/pikoci/pikoci/pikoci/oauthprovider Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	oauthprovider "github.com/pikoci/pikoci/pikoci/oauthprovider"
	gomock "go.uber.org/mock/gomock"
)

// OAuthProviderRepository is a mock of Repository interface.
type OAuthProviderRepository struct {
	ctrl     *gomock.Controller
	recorder *OAuthProviderRepositoryMockRecorder
	isgomock struct{}
}

// OAuthProviderRepositoryMockRecorder is the mock recorder for OAuthProviderRepository.
type OAuthProviderRepositoryMockRecorder struct {
	mock *OAuthProviderRepository
}

// NewOAuthProviderRepository creates a new mock instance.
func NewOAuthProviderRepository(ctrl *gomock.Controller) *OAuthProviderRepository {
	mock := &OAuthProviderRepository{ctrl: ctrl}
	mock.recorder = &OAuthProviderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *OAuthProviderRepository) EXPECT() *OAuthProviderRepositoryMockRecorder {
	return m.recorder
}

// CreateProvider mocks base method.
func (m *OAuthProviderRepository) CreateProvider(ctx context.Context, p oauthprovider.Provider) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProvider", ctx, p)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProvider indicates an expected call of CreateProvider.
func (mr *OAuthProviderRepositoryMockRecorder) CreateProvider(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProvider", reflect.TypeOf((*OAuthProviderRepository)(nil).CreateProvider), ctx, p)
}

// CreateUserLink mocks base method.
func (m *OAuthProviderRepository) CreateUserLink(ctx context.Context, link oauthprovider.UserLink) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserLink", ctx, link)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserLink indicates an expected call of CreateUserLink.
func (mr *OAuthProviderRepositoryMockRecorder) CreateUserLink(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserLink", reflect.TypeOf((*OAuthProviderRepository)(nil).CreateUserLink), ctx, link)
}

// DeleteProvider mocks base method.
func (m *OAuthProviderRepository) DeleteProvider(ctx context.Context, canonical string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProvider", ctx, canonical)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProvider indicates an expected call of DeleteProvider.
func (mr *OAuthProviderRepositoryMockRecorder) DeleteProvider(ctx, canonical any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProvider", reflect.TypeOf((*OAuthProviderRepository)(nil).DeleteProvider), ctx, canonical)
}

// DeleteUserLink mocks base method.
func (m *OAuthProviderRepository) DeleteUserLink(ctx context.Context, id uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserLink", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserLink indicates an expected call of DeleteUserLink.
func (mr *OAuthProviderRepositoryMockRecorder) DeleteUserLink(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserLink", reflect.TypeOf((*OAuthProviderRepository)(nil).DeleteUserLink), ctx, id)
}

// DeleteUserLinkByUserAndProvider mocks base method.
func (m *OAuthProviderRepository) DeleteUserLinkByUserAndProvider(ctx context.Context, userID, providerID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserLinkByUserAndProvider", ctx, userID, providerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserLinkByUserAndProvider indicates an expected call of DeleteUserLinkByUserAndProvider.
func (mr *OAuthProviderRepositoryMockRecorder) DeleteUserLinkByUserAndProvider(ctx, userID, providerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserLinkByUserAndProvider", reflect.TypeOf((*OAuthProviderRepository)(nil).DeleteUserLinkByUserAndProvider), ctx, userID, providerID)
}

// FilterEnabledProviders mocks base method.
func (m *OAuthProviderRepository) FilterEnabledProviders(ctx context.Context) ([]*oauthprovider.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterEnabledProviders", ctx)
	ret0, _ := ret[0].([]*oauthprovider.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterEnabledProviders indicates an expected call of FilterEnabledProviders.
func (mr *OAuthProviderRepositoryMockRecorder) FilterEnabledProviders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterEnabledProviders", reflect.TypeOf((*OAuthProviderRepository)(nil).FilterEnabledProviders), ctx)
}

// FilterProviders mocks base method.
func (m *OAuthProviderRepository) FilterProviders(ctx context.Context) ([]*oauthprovider.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterProviders", ctx)
	ret0, _ := ret[0].([]*oauthprovider.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterProviders indicates an expected call of FilterProviders.
func (mr *OAuthProviderRepositoryMockRecorder) FilterProviders(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterProviders", reflect.TypeOf((*OAuthProviderRepository)(nil).FilterProviders), ctx)
}

// FindProvider mocks base method.
func (m *OAuthProviderRepository) FindProvider(ctx context.Context, id uint32) (*oauthprovider.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProvider", ctx, id)
	ret0, _ := ret[0].(*oauthprovider.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProvider indicates an expected call of FindProvider.
func (mr *OAuthProviderRepositoryMockRecorder) FindProvider(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProvider", reflect.TypeOf((*OAuthProviderRepository)(nil).FindProvider), ctx, id)
}

// FindProviderByCanonical mocks base method.
func (m *OAuthProviderRepository) FindProviderByCanonical(ctx context.Context, canonical string) (*oauthprovider.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProviderByCanonical", ctx, canonical)
	ret0, _ := ret[0].(*oauthprovider.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProviderByCanonical indicates an expected call of FindProviderByCanonical.
func (mr *OAuthProviderRepositoryMockRecorder) FindProviderByCanonical(ctx, canonical any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProviderByCanonical", reflect.TypeOf((*OAuthProviderRepository)(nil).FindProviderByCanonical), ctx, canonical)
}

// FindUserLink mocks base method.
func (m *OAuthProviderRepository) FindUserLink(ctx context.Context, providerID uint32, subject string) (*oauthprovider.UserLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserLink", ctx, providerID, subject)
	ret0, _ := ret[0].(*oauthprovider.UserLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserLink indicates an expected call of FindUserLink.
func (mr *OAuthProviderRepositoryMockRecorder) FindUserLink(ctx, providerID, subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserLink", reflect.TypeOf((*OAuthProviderRepository)(nil).FindUserLink), ctx, providerID, subject)
}

// FindUserLinksByUser mocks base method.
func (m *OAuthProviderRepository) FindUserLinksByUser(ctx context.Context, userID uint32) ([]*oauthprovider.UserLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserLinksByUser", ctx, userID)
	ret0, _ := ret[0].([]*oauthprovider.UserLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserLinksByUser indicates an expected call of FindUserLinksByUser.
func (mr *OAuthProviderRepositoryMockRecorder) FindUserLinksByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserLinksByUser", reflect.TypeOf((*OAuthProviderRepository)(nil).FindUserLinksByUser), ctx, userID)
}

// GetAuthSettings mocks base method.
func (m *OAuthProviderRepository) GetAuthSettings(ctx context.Context) (*oauthprovider.AuthSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthSettings", ctx)
	ret0, _ := ret[0].(*oauthprovider.AuthSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthSettings indicates an expected call of GetAuthSettings.
func (mr *OAuthProviderRepositoryMockRecorder) GetAuthSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthSettings", reflect.TypeOf((*OAuthProviderRepository)(nil).GetAuthSettings), ctx)
}

// UpdateAuthSettings mocks base method.
func (m *OAuthProviderRepository) UpdateAuthSettings(ctx context.Context, settings oauthprovider.AuthSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAuthSettings", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAuthSettings indicates an expected call of UpdateAuthSettings.
func (mr *OAuthProviderRepositoryMockRecorder) UpdateAuthSettings(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAuthSettings", reflect.TypeOf((*OAuthProviderRepository)(nil).UpdateAuthSettings), ctx, settings)
}

// UpdateProvider mocks base method.
func (m *OAuthProviderRepository) UpdateProvider(ctx context.Context, canonical string, p oauthprovider.Provider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProvider", ctx, canonical, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProvider indicates an expected call of UpdateProvider.
func (mr *OAuthProviderRepositoryMockRecorder) UpdateProvider(ctx, canonical, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProvider", reflect.TypeOf((*OAuthProviderRepository)(nil).UpdateProvider), ctx, canonical, p)
}
