// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pikoci/pikoci/pikoci/secret (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/secret_repository.go -mock_names=Repository=SecretRepository -package mock github.com/pikoci/pikoci/pikoci/secret Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	secret "github.com/pikoci/pikoci/pikoci/secret"
	gomock "go.uber.org/mock/gomock"
)

// SecretRepository is a mock of Repository interface.
type SecretRepository struct {
	ctrl     *gomock.Controller
	recorder *SecretRepositoryMockRecorder
	isgomock struct{}
}

// SecretRepositoryMockRecorder is the mock recorder for SecretRepository.
type SecretRepositoryMockRecorder struct {
	mock *SecretRepository
}

// NewSecretRepository creates a new mock instance.
func NewSecretRepository(ctrl *gomock.Controller) *SecretRepository {
	mock := &SecretRepository{ctrl: ctrl}
	mock.recorder = &SecretRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *SecretRepository) EXPECT() *SecretRepositoryMockRecorder {
	return m.recorder
}

// CreateServerKey mocks base method.
func (m *SecretRepository) CreateServerKey(ctx context.Context, k secret.ServerKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServerKey", ctx, k)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateServerKey indicates an expected call of CreateServerKey.
func (mr *SecretRepositoryMockRecorder) CreateServerKey(ctx, k any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServerKey", reflect.TypeOf((*SecretRepository)(nil).CreateServerKey), ctx, k)
}

// DeletePipeline mocks base method.
func (m *SecretRepository) DeletePipeline(ctx context.Context, tc, pn, canonical string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePipeline", ctx, tc, pn, canonical)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePipeline indicates an expected call of DeletePipeline.
func (mr *SecretRepositoryMockRecorder) DeletePipeline(ctx, tc, pn, canonical any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePipeline", reflect.TypeOf((*SecretRepository)(nil).DeletePipeline), ctx, tc, pn, canonical)
}

// DeleteTeam mocks base method.
func (m *SecretRepository) DeleteTeam(ctx context.Context, tc, canonical string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTeam", ctx, tc, canonical)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTeam indicates an expected call of DeleteTeam.
func (mr *SecretRepositoryMockRecorder) DeleteTeam(ctx, tc, canonical any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTeam", reflect.TypeOf((*SecretRepository)(nil).DeleteTeam), ctx, tc, canonical)
}

// FilterPipeline mocks base method.
func (m *SecretRepository) FilterPipeline(ctx context.Context, tc, pn string) ([]*secret.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterPipeline", ctx, tc, pn)
	ret0, _ := ret[0].([]*secret.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterPipeline indicates an expected call of FilterPipeline.
func (mr *SecretRepositoryMockRecorder) FilterPipeline(ctx, tc, pn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterPipeline", reflect.TypeOf((*SecretRepository)(nil).FilterPipeline), ctx, tc, pn)
}

// FilterTeam mocks base method.
func (m *SecretRepository) FilterTeam(ctx context.Context, tc string) ([]*secret.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterTeam", ctx, tc)
	ret0, _ := ret[0].([]*secret.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterTeam indicates an expected call of FilterTeam.
func (mr *SecretRepositoryMockRecorder) FilterTeam(ctx, tc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterTeam", reflect.TypeOf((*SecretRepository)(nil).FilterTeam), ctx, tc)
}

// FindServerKey mocks base method.
func (m *SecretRepository) FindServerKey(ctx context.Context) (*secret.ServerKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindServerKey", ctx)
	ret0, _ := ret[0].(*secret.ServerKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindServerKey indicates an expected call of FindServerKey.
func (mr *SecretRepositoryMockRecorder) FindServerKey(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindServerKey", reflect.TypeOf((*SecretRepository)(nil).FindServerKey), ctx)
}

// StoredValues mocks base method.
func (m *SecretRepository) StoredValues(ctx context.Context, tc, pn string) (map[string]secret.StoredValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoredValues", ctx, tc, pn)
	ret0, _ := ret[0].(map[string]secret.StoredValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoredValues indicates an expected call of StoredValues.
func (mr *SecretRepositoryMockRecorder) StoredValues(ctx, tc, pn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoredValues", reflect.TypeOf((*SecretRepository)(nil).StoredValues), ctx, tc, pn)
}

// UpsertPipeline mocks base method.
func (m *SecretRepository) UpsertPipeline(ctx context.Context, tc, pn string, e secret.Entry, value []byte) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPipeline", ctx, tc, pn, e, value)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertPipeline indicates an expected call of UpsertPipeline.
func (mr *SecretRepositoryMockRecorder) UpsertPipeline(ctx, tc, pn, e, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPipeline", reflect.TypeOf((*SecretRepository)(nil).UpsertPipeline), ctx, tc, pn, e, value)
}

// UpsertTeam mocks base method.
func (m *SecretRepository) UpsertTeam(ctx context.Context, tc string, e secret.Entry, value []byte) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTeam", ctx, tc, e, value)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertTeam indicates an expected call of UpsertTeam.
func (mr *SecretRepositoryMockRecorder) UpsertTeam(ctx, tc, e, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTeam", reflect.TypeOf((*SecretRepository)(nil).UpsertTeam), ctx, tc, e, value)
}
