// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pikoci/pikoci/pikoci (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=mock/service.go -mock_names=Service=Service -package mock github.com/pikoci/pikoci/pikoci Service
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	apitoken "github.com/pikoci/pikoci/pikoci/apitoken"
	auditlog "github.com/pikoci/pikoci/pikoci/auditlog"
	build "github.com/pikoci/pikoci/pikoci/build"
	job "github.com/pikoci/pikoci/pikoci/job"
	pipeline "github.com/pikoci/pikoci/pikoci/pipeline"
	resource "github.com/pikoci/pikoci/pikoci/resource"
	role "github.com/pikoci/pikoci/pikoci/role"
	team "github.com/pikoci/pikoci/pikoci/team"
	trigger "github.com/pikoci/pikoci/pikoci/trigger"
	user "github.com/pikoci/pikoci/pikoci/user"
	wkr "github.com/pikoci/pikoci/pikoci/wkr"
	gomock "go.uber.org/mock/gomock"
)

// Service is a mock of Service interface.
type Service struct {
	ctrl     *gomock.Controller
	recorder *ServiceMockRecorder
	isgomock struct{}
}

// ServiceMockRecorder is the mock recorder for Service.
type ServiceMockRecorder struct {
	mock *Service
}

// NewService creates a new mock instance.
func NewService(ctrl *gomock.Controller) *Service {
	mock := &Service{ctrl: ctrl}
	mock.recorder = &ServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Service) EXPECT() *ServiceMockRecorder {
	return m.recorder
}

// ApproveBuild mocks base method.
func (m *Service) ApproveBuild(ctx context.Context, tc, pc, jn, buildNumber, username, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveBuild", ctx, tc, pc, jn, buildNumber, username, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveBuild indicates an expected call of ApproveBuild.
func (mr *ServiceMockRecorder) ApproveBuild(ctx, tc, pc, jn, buildNumber, username, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveBuild", reflect.TypeOf((*Service)(nil).ApproveBuild), ctx, tc, pc, jn, buildNumber, username, message)
}

// CancelJobBuild mocks base method.
func (m *Service) CancelJobBuild(ctx context.Context, tc, pn, jn, buildNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelJobBuild", ctx, tc, pn, jn, buildNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelJobBuild indicates an expected call of CancelJobBuild.
func (mr *ServiceMockRecorder) CancelJobBuild(ctx, tc, pn, jn, buildNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelJobBuild", reflect.TypeOf((*Service)(nil).CancelJobBuild), ctx, tc, pn, jn, buildNumber)
}

// ChangePassword mocks base method.
func (m *Service) ChangePassword(ctx context.Context, un, oldPassword, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, un, oldPassword, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *ServiceMockRecorder) ChangePassword(ctx, un, oldPassword, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*Service)(nil).ChangePassword), ctx, un, oldPassword, newPassword)
}

// CreateApiToken mocks base method.
func (m *Service) CreateApiToken(ctx context.Context, username, name string, personal bool, teamCanonical string, tokenRole role.Role, expiresAt *time.Time) (*apitoken.WithPlaintext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApiToken", ctx, username, name, personal, teamCanonical, tokenRole, expiresAt)
	ret0, _ := ret[0].(*apitoken.WithPlaintext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApiToken indicates an expected call of CreateApiToken.
func (mr *ServiceMockRecorder) CreateApiToken(ctx, username, name, personal, teamCanonical, tokenRole, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApiToken", reflect.TypeOf((*Service)(nil).CreateApiToken), ctx, username, name, personal, teamCanonical, tokenRole, expiresAt)
}

// CreateJobBuild mocks base method.
func (m *Service) CreateJobBuild(ctx context.Context, tc, pn, jn string, b build.Build) (*build.Build, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJobBuild", ctx, tc, pn, jn, b)
	ret0, _ := ret[0].(*build.Build)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJobBuild indicates an expected call of CreateJobBuild.
func (mr *ServiceMockRecorder) CreateJobBuild(ctx, tc, pn, jn, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJobBuild", reflect.TypeOf((*Service)(nil).CreateJobBuild), ctx, tc, pn, jn, b)
}

// CreatePipeline mocks base method.
func (m *Service) CreatePipeline(ctx context.Context, tc, pn string, pp []byte, vars map[string]any) (*pipeline.Pipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePipeline", ctx, tc, pn, pp, vars)
	ret0, _ := ret[0].(*pipeline.Pipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePipeline indicates an expected call of CreatePipeline.
func (mr *ServiceMockRecorder) CreatePipeline(ctx, tc, pn, pp, vars any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePipeline", reflect.TypeOf((*Service)(nil).CreatePipeline), ctx, tc, pn, pp, vars)
}

// CreatePipelineImage mocks base method.
func (m *Service) CreatePipelineImage(ctx context.Context, tc string, pp []byte, vars map[string]any, format string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePipelineImage", ctx, tc, pp, vars, format)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePipelineImage indicates an expected call of CreatePipelineImage.
func (mr *ServiceMockRecorder) CreatePipelineImage(ctx, tc, pp, vars, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePipelineImage", reflect.TypeOf((*Service)(nil).CreatePipelineImage), ctx, tc, pp, vars, format)
}

// CreateResourceVersion mocks base method.
func (m *Service) CreateResourceVersion(ctx context.Context, tc, pn, rCan string, v resource.Version) (*resource.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResourceVersion", ctx, tc, pn, rCan, v)
	ret0, _ := ret[0].(*resource.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateResourceVersion indicates an expected call of CreateResourceVersion.
func (mr *ServiceMockRecorder) CreateResourceVersion(ctx, tc, pn, rCan, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResourceVersion", reflect.TypeOf((*Service)(nil).CreateResourceVersion), ctx, tc, pn, rCan, v)
}

// CreateRetryJobBuild mocks base method.
func (m *Service) CreateRetryJobBuild(ctx context.Context, tc, pn, jn, parentBuildNumber string, b build.Build) (*build.Build, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRetryJobBuild", ctx, tc, pn, jn, parentBuildNumber, b)
	ret0, _ := ret[0].(*build.Build)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRetryJobBuild indicates an expected call of CreateRetryJobBuild.
func (mr *ServiceMockRecorder) CreateRetryJobBuild(ctx, tc, pn, jn, parentBuildNumber, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRetryJobBuild", reflect.TypeOf((*Service)(nil).CreateRetryJobBuild), ctx, tc, pn, jn, parentBuildNumber, b)
}

// CreateTeam mocks base method.
func (m *Service) CreateTeam(ctx context.Context, un string, t team.Team) (*team.WithMembers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeam", ctx, un, t)
	ret0, _ := ret[0].(*team.WithMembers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *ServiceMockRecorder) CreateTeam(ctx, un, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*Service)(nil).CreateTeam), ctx, un, t)
}

// CreateTeamMember mocks base method.
func (m *Service) CreateTeamMember(ctx context.Context, tc string, tm team.Member) (*team.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeamMember", ctx, tc, tm)
	ret0, _ := ret[0].(*team.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTeamMember indicates an expected call of CreateTeamMember.
func (mr *ServiceMockRecorder) CreateTeamMember(ctx, tc, tm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeamMember", reflect.TypeOf((*Service)(nil).CreateTeamMember), ctx, tc, tm)
}

// CreateTrigger mocks base method.
func (m *Service) CreateTrigger(ctx context.Context, tc, name string, version map[string]any) (*trigger.Trigger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTrigger", ctx, tc, name, version)
	ret0, _ := ret[0].(*trigger.Trigger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTrigger indicates an expected call of CreateTrigger.
func (mr *ServiceMockRecorder) CreateTrigger(ctx, tc, name, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTrigger", reflect.TypeOf((*Service)(nil).CreateTrigger), ctx, tc, name, version)
}

// CreateUser mocks base method.
func (m *Service) CreateUser(ctx context.Context, u user.User, isHash bool) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, u, isHash)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *ServiceMockRecorder) CreateUser(ctx, u, isHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*Service)(nil).CreateUser), ctx, u, isHash)
}

// DeleteApiToken mocks base method.
func (m *Service) DeleteApiToken(ctx context.Context, username string, tokenID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteApiToken", ctx, username, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteApiToken indicates an expected call of DeleteApiToken.
func (mr *ServiceMockRecorder) DeleteApiToken(ctx, username, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApiToken", reflect.TypeOf((*Service)(nil).DeleteApiToken), ctx, username, tokenID)
}

// DeleteJobBuild mocks base method.
func (m *Service) DeleteJobBuild(ctx context.Context, tc, pn, jn, buildNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJobBuild", ctx, tc, pn, jn, buildNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteJobBuild indicates an expected call of DeleteJobBuild.
func (mr *ServiceMockRecorder) DeleteJobBuild(ctx, tc, pn, jn, buildNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJobBuild", reflect.TypeOf((*Service)(nil).DeleteJobBuild), ctx, tc, pn, jn, buildNumber)
}

// DeletePipeline mocks base method.
func (m *Service) DeletePipeline(ctx context.Context, tc, pn string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePipeline", ctx, tc, pn)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePipeline indicates an expected call of DeletePipeline.
func (mr *ServiceMockRecorder) DeletePipeline(ctx, tc, pn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePipeline", reflect.TypeOf((*Service)(nil).DeletePipeline), ctx, tc, pn)
}

// DeleteTeam mocks base method.
func (m *Service) DeleteTeam(ctx context.Context, tc string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTeam", ctx, tc)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTeam indicates an expected call of DeleteTeam.
func (mr *ServiceMockRecorder) DeleteTeam(ctx, tc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTeam", reflect.TypeOf((*Service)(nil).DeleteTeam), ctx, tc)
}

// DeleteTeamMember mocks base method.
func (m *Service) DeleteTeamMember(ctx context.Context, tc, mc string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTeamMember", ctx, tc, mc)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTeamMember indicates an expected call of DeleteTeamMember.
func (mr *ServiceMockRecorder) DeleteTeamMember(ctx, tc, mc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTeamMember", reflect.TypeOf((*Service)(nil).DeleteTeamMember), ctx, tc, mc)
}

// DeleteUser mocks base method.
func (m *Service) DeleteUser(ctx context.Context, un string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, un)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *ServiceMockRecorder) DeleteUser(ctx, un any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*Service)(nil).DeleteUser), ctx, un)
}

// DeleteWorker mocks base method.
func (m *Service) DeleteWorker(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorker", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorker indicates an expected call of DeleteWorker.
func (mr *ServiceMockRecorder) DeleteWorker(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorker", reflect.TypeOf((*Service)(nil).DeleteWorker), ctx, name)
}

// EvaluateDownstreamJobs mocks base method.
func (m *Service) EvaluateDownstreamJobs(ctx context.Context, tc, pn, completedJobName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvaluateDownstreamJobs", ctx, tc, pn, completedJobName)
	ret0, _ := ret[0].(error)
	return ret0
}

// EvaluateDownstreamJobs indicates an expected call of EvaluateDownstreamJobs.
func (mr *ServiceMockRecorder) EvaluateDownstreamJobs(ctx, tc, pn, completedJobName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvaluateDownstreamJobs", reflect.TypeOf((*Service)(nil).EvaluateDownstreamJobs), ctx, tc, pn, completedJobName)
}

// FindApiTokenByHash mocks base method.
func (m *Service) FindApiTokenByHash(ctx context.Context, tokenHash string) (*apitoken.AuthResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindApiTokenByHash", ctx, tokenHash)
	ret0, _ := ret[0].(*apitoken.AuthResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindApiTokenByHash indicates an expected call of FindApiTokenByHash.
func (mr *ServiceMockRecorder) FindApiTokenByHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindApiTokenByHash", reflect.TypeOf((*Service)(nil).FindApiTokenByHash), ctx, tokenHash)
}

// FindBuildGetVersions mocks base method.
func (m *Service) FindBuildGetVersions(ctx context.Context, tc, pn, jn string, buildID uint32) (map[string]uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBuildGetVersions", ctx, tc, pn, jn, buildID)
	ret0, _ := ret[0].(map[string]uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBuildGetVersions indicates an expected call of FindBuildGetVersions.
func (mr *ServiceMockRecorder) FindBuildGetVersions(ctx, tc, pn, jn, buildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBuildGetVersions", reflect.TypeOf((*Service)(nil).FindBuildGetVersions), ctx, tc, pn, jn, buildID)
}

// FindOldestPendingBuild mocks base method.
func (m *Service) FindOldestPendingBuild(ctx context.Context, tc, pn, jn string) (*build.Build, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOldestPendingBuild", ctx, tc, pn, jn)
	ret0, _ := ret[0].(*build.Build)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOldestPendingBuild indicates an expected call of FindOldestPendingBuild.
func (mr *ServiceMockRecorder) FindOldestPendingBuild(ctx, tc, pn, jn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOldestPendingBuild", reflect.TypeOf((*Service)(nil).FindOldestPendingBuild), ctx, tc, pn, jn)
}

// GenerateTeamWorkerToken mocks base method.
func (m *Service) GenerateTeamWorkerToken(ctx context.Context, tc string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTeamWorkerToken", ctx, tc)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTeamWorkerToken indicates an expected call of GenerateTeamWorkerToken.
func (mr *ServiceMockRecorder) GenerateTeamWorkerToken(ctx, tc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTeamWorkerToken", reflect.TypeOf((*Service)(nil).GenerateTeamWorkerToken), ctx, tc)
}

// GetBuildReport mocks base method.
func (m *Service) GetBuildReport(ctx context.Context, tc, pn, jn, buildNumber string) (*build.BuildReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuildReport", ctx, tc, pn, jn, buildNumber)
	ret0, _ := ret[0].(*build.BuildReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuildReport indicates an expected call of GetBuildReport.
func (mr *ServiceMockRecorder) GetBuildReport(ctx, tc, pn, jn, buildNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuildReport", reflect.TypeOf((*Service)(nil).GetBuildReport), ctx, tc, pn, jn, buildNumber)
}

// GetJobBuild mocks base method.
func (m *Service) GetJobBuild(ctx context.Context, tc, pn, jn, buildNumber string) (*build.Build, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobBuild", ctx, tc, pn, jn, buildNumber)
	ret0, _ := ret[0].(*build.Build)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobBuild indicates an expected call of GetJobBuild.
func (mr *ServiceMockRecorder) GetJobBuild(ctx, tc, pn, jn, buildNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobBuild", reflect.TypeOf((*Service)(nil).GetJobBuild), ctx, tc, pn, jn, buildNumber)
}

// GetPipeline mocks base method.
func (m *Service) GetPipeline(ctx context.Context, tc, pn string) (*pipeline.Pipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipeline", ctx, tc, pn)
	ret0, _ := ret[0].(*pipeline.Pipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPipeline indicates an expected call of GetPipeline.
func (mr *ServiceMockRecorder) GetPipeline(ctx, tc, pn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipeline", reflect.TypeOf((*Service)(nil).GetPipeline), ctx, tc, pn)
}

// GetPipelineImage mocks base method.
func (m *Service) GetPipelineImage(ctx context.Context, tc, pn, format string, hideIntermediates, groupParallel bool, versionID *uint32) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipelineImage", ctx, tc, pn, format, hideIntermediates, groupParallel, versionID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPipelineImage indicates an expected call of GetPipelineImage.
func (mr *ServiceMockRecorder) GetPipelineImage(ctx, tc, pn, format, hideIntermediates, groupParallel, versionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipelineImage", reflect.TypeOf((*Service)(nil).GetPipelineImage), ctx, tc, pn, format, hideIntermediates, groupParallel, versionID)
}

// GetPipelineJob mocks base method.
func (m *Service) GetPipelineJob(ctx context.Context, tc, pn, jn string) (*job.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipelineJob", ctx, tc, pn, jn)
	ret0, _ := ret[0].(*job.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPipelineJob indicates an expected call of GetPipelineJob.
func (mr *ServiceMockRecorder) GetPipelineJob(ctx, tc, pn, jn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipelineJob", reflect.TypeOf((*Service)(nil).GetPipelineJob), ctx, tc, pn, jn)
}

// GetPipelineResource mocks base method.
func (m *Service) GetPipelineResource(ctx context.Context, tc, pn, rCan string) (*resource.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipelineResource", ctx, tc, pn, rCan)
	ret0, _ := ret[0].(*resource.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPipelineResource indicates an expected call of GetPipelineResource.
func (mr *ServiceMockRecorder) GetPipelineResource(ctx, tc, pn, rCan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipelineResource", reflect.TypeOf((*Service)(nil).GetPipelineResource), ctx, tc, pn, rCan)
}

// GetPublicPipeline mocks base method.
func (m *Service) GetPublicPipeline(ctx context.Context, tc, pn string) (*pipeline.Pipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicPipeline", ctx, tc, pn)
	ret0, _ := ret[0].(*pipeline.Pipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicPipeline indicates an expected call of GetPublicPipeline.
func (mr *ServiceMockRecorder) GetPublicPipeline(ctx, tc, pn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicPipeline", reflect.TypeOf((*Service)(nil).GetPublicPipeline), ctx, tc, pn)
}

// GetPublicPipelineImage mocks base method.
func (m *Service) GetPublicPipelineImage(ctx context.Context, tc, pn, format string, hideIntermediates, groupParallel bool, versionID *uint32) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicPipelineImage", ctx, tc, pn, format, hideIntermediates, groupParallel, versionID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicPipelineImage indicates an expected call of GetPublicPipelineImage.
func (mr *ServiceMockRecorder) GetPublicPipelineImage(ctx, tc, pn, format, hideIntermediates, groupParallel, versionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicPipelineImage", reflect.TypeOf((*Service)(nil).GetPublicPipelineImage), ctx, tc, pn, format, hideIntermediates, groupParallel, versionID)
}

// GetPublicPipelineJob mocks base method.
func (m *Service) GetPublicPipelineJob(ctx context.Context, tc, pn, jn string) (*job.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicPipelineJob", ctx, tc, pn, jn)
	ret0, _ := ret[0].(*job.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicPipelineJob indicates an expected call of GetPublicPipelineJob.
func (mr *ServiceMockRecorder) GetPublicPipelineJob(ctx, tc, pn, jn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicPipelineJob", reflect.TypeOf((*Service)(nil).GetPublicPipelineJob), ctx, tc, pn, jn)
}

// GetPublicPipelineResource mocks base method.
func (m *Service) GetPublicPipelineResource(ctx context.Context, tc, pn, rCan string) (*resource.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicPipelineResource", ctx, tc, pn, rCan)
	ret0, _ := ret[0].(*resource.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicPipelineResource indicates an expected call of GetPublicPipelineResource.
func (mr *ServiceMockRecorder) GetPublicPipelineResource(ctx, tc, pn, rCan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicPipelineResource", reflect.TypeOf((*Service)(nil).GetPublicPipelineResource), ctx, tc, pn, rCan)
}

// GetPublicResourceVersionPath mocks base method.
func (m *Service) GetPublicResourceVersionPath(ctx context.Context, tc, pn, rCan string, versionID uint32) (*resource.VersionPathResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicResourceVersionPath", ctx, tc, pn, rCan, versionID)
	ret0, _ := ret[0].(*resource.VersionPathResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicResourceVersionPath indicates an expected call of GetPublicResourceVersionPath.
func (mr *ServiceMockRecorder) GetPublicResourceVersionPath(ctx, tc, pn, rCan, versionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicResourceVersionPath", reflect.TypeOf((*Service)(nil).GetPublicResourceVersionPath), ctx, tc, pn, rCan, versionID)
}

// GetResourceVersionPath mocks base method.
func (m *Service) GetResourceVersionPath(ctx context.Context, tc, pn, rCan string, versionID uint32) (*resource.VersionPathResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceVersionPath", ctx, tc, pn, rCan, versionID)
	ret0, _ := ret[0].(*resource.VersionPathResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResourceVersionPath indicates an expected call of GetResourceVersionPath.
func (mr *ServiceMockRecorder) GetResourceVersionPath(ctx, tc, pn, rCan, versionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceVersionPath", reflect.TypeOf((*Service)(nil).GetResourceVersionPath), ctx, tc, pn, rCan, versionID)
}

// GetTeam mocks base method.
func (m *Service) GetTeam(ctx context.Context, tc string) (*team.WithMembers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeam", ctx, tc)
	ret0, _ := ret[0].(*team.WithMembers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeam indicates an expected call of GetTeam.
func (mr *ServiceMockRecorder) GetTeam(ctx, tc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeam", reflect.TypeOf((*Service)(nil).GetTeam), ctx, tc)
}

// GetTeamWorkerToken mocks base method.
func (m *Service) GetTeamWorkerToken(ctx context.Context, tc string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamWorkerToken", ctx, tc)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamWorkerToken indicates an expected call of GetTeamWorkerToken.
func (mr *ServiceMockRecorder) GetTeamWorkerToken(ctx, tc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamWorkerToken", reflect.TypeOf((*Service)(nil).GetTeamWorkerToken), ctx, tc)
}

// GetUser mocks base method.
func (m *Service) GetUser(ctx context.Context, un string) (*user.WithMemberships, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, un)
	ret0, _ := ret[0].(*user.WithMemberships)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *ServiceMockRecorder) GetUser(ctx, un any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*Service)(nil).GetUser), ctx, un)
}

// InsertBuildGetVersion mocks base method.
func (m *Service) InsertBuildGetVersion(ctx context.Context, tc, pn, jn string, buildID uint32, stepName string, versionID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBuildGetVersion", ctx, tc, pn, jn, buildID, stepName, versionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBuildGetVersion indicates an expected call of InsertBuildGetVersion.
func (mr *ServiceMockRecorder) InsertBuildGetVersion(ctx, tc, pn, jn, buildID, stepName, versionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBuildGetVersion", reflect.TypeOf((*Service)(nil).InsertBuildGetVersion), ctx, tc, pn, jn, buildID, stepName, versionID)
}

// ListApiTokens mocks base method.
func (m *Service) ListApiTokens(ctx context.Context, username string) ([]*apitoken.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListApiTokens", ctx, username)
	ret0, _ := ret[0].([]*apitoken.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListApiTokens indicates an expected call of ListApiTokens.
func (mr *ServiceMockRecorder) ListApiTokens(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApiTokens", reflect.TypeOf((*Service)(nil).ListApiTokens), ctx, username)
}

// ListAuditLog mocks base method.
func (m *Service) ListAuditLog(ctx context.Context, tc string, opts auditlog.FilterOpts) ([]*auditlog.Entry, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuditLog", ctx, tc, opts)
	ret0, _ := ret[0].([]*auditlog.Entry)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAuditLog indicates an expected call of ListAuditLog.
func (mr *ServiceMockRecorder) ListAuditLog(ctx, tc, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuditLog", reflect.TypeOf((*Service)(nil).ListAuditLog), ctx, tc, opts)
}

// ListJobBuilds mocks base method.
func (m *Service) ListJobBuilds(ctx context.Context, tc, pn, jn string, before, after *uint32, limit uint32, statuses []build.Status) ([]*build.Build, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJobBuilds", ctx, tc, pn, jn, before, after, limit, statuses)
	ret0, _ := ret[0].([]*build.Build)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListJobBuilds indicates an expected call of ListJobBuilds.
func (mr *ServiceMockRecorder) ListJobBuilds(ctx, tc, pn, jn, before, after, limit, statuses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobBuilds", reflect.TypeOf((*Service)(nil).ListJobBuilds), ctx, tc, pn, jn, before, after, limit, statuses)
}

// ListPipelineJobs mocks base method.
func (m *Service) ListPipelineJobs(ctx context.Context, tc, pn string) ([]job.WithStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPipelineJobs", ctx, tc, pn)
	ret0, _ := ret[0].([]job.WithStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPipelineJobs indicates an expected call of ListPipelineJobs.
func (mr *ServiceMockRecorder) ListPipelineJobs(ctx, tc, pn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPipelineJobs", reflect.TypeOf((*Service)(nil).ListPipelineJobs), ctx, tc, pn)
}

// ListPipelineResources mocks base method.
func (m *Service) ListPipelineResources(ctx context.Context, tc, pn string) ([]*resource.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPipelineResources", ctx, tc, pn)
	ret0, _ := ret[0].([]*resource.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPipelineResources indicates an expected call of ListPipelineResources.
func (mr *ServiceMockRecorder) ListPipelineResources(ctx, tc, pn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPipelineResources", reflect.TypeOf((*Service)(nil).ListPipelineResources), ctx, tc, pn)
}

// ListPipelines mocks base method.
func (m *Service) ListPipelines(ctx context.Context, tc string) ([]*pipeline.Pipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPipelines", ctx, tc)
	ret0, _ := ret[0].([]*pipeline.Pipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPipelines indicates an expected call of ListPipelines.
func (mr *ServiceMockRecorder) ListPipelines(ctx, tc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPipelines", reflect.TypeOf((*Service)(nil).ListPipelines), ctx, tc)
}

// ListPublicJobBuilds mocks base method.
func (m *Service) ListPublicJobBuilds(ctx context.Context, tc, pn, jn string, before, after *uint32, limit uint32, statuses []build.Status) ([]*build.Build, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublicJobBuilds", ctx, tc, pn, jn, before, after, limit, statuses)
	ret0, _ := ret[0].([]*build.Build)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPublicJobBuilds indicates an expected call of ListPublicJobBuilds.
func (mr *ServiceMockRecorder) ListPublicJobBuilds(ctx, tc, pn, jn, before, after, limit, statuses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublicJobBuilds", reflect.TypeOf((*Service)(nil).ListPublicJobBuilds), ctx, tc, pn, jn, before, after, limit, statuses)
}

// ListPublicPipelineJobs mocks base method.
func (m *Service) ListPublicPipelineJobs(ctx context.Context, tc, pn string) ([]job.WithStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublicPipelineJobs", ctx, tc, pn)
	ret0, _ := ret[0].([]job.WithStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublicPipelineJobs indicates an expected call of ListPublicPipelineJobs.
func (mr *ServiceMockRecorder) ListPublicPipelineJobs(ctx, tc, pn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublicPipelineJobs", reflect.TypeOf((*Service)(nil).ListPublicPipelineJobs), ctx, tc, pn)
}

// ListPublicPipelineResources mocks base method.
func (m *Service) ListPublicPipelineResources(ctx context.Context, tc, pn string) ([]*resource.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublicPipelineResources", ctx, tc, pn)
	ret0, _ := ret[0].([]*resource.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublicPipelineResources indicates an expected call of ListPublicPipelineResources.
func (mr *ServiceMockRecorder) ListPublicPipelineResources(ctx, tc, pn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublicPipelineResources", reflect.TypeOf((*Service)(nil).ListPublicPipelineResources), ctx, tc, pn)
}

// ListPublicResourceVersions mocks base method.
func (m *Service) ListPublicResourceVersions(ctx context.Context, tc, pn, rCan string, before, after *uint32, limit uint32) ([]*resource.Version, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublicResourceVersions", ctx, tc, pn, rCan, before, after, limit)
	ret0, _ := ret[0].([]*resource.Version)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPublicResourceVersions indicates an expected call of ListPublicResourceVersions.
func (mr *ServiceMockRecorder) ListPublicResourceVersions(ctx, tc, pn, rCan, before, after, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublicResourceVersions", reflect.TypeOf((*Service)(nil).ListPublicResourceVersions), ctx, tc, pn, rCan, before, after, limit)
}

// ListResourceVersions mocks base method.
func (m *Service) ListResourceVersions(ctx context.Context, tc, pn, rCan string, before, after *uint32, limit uint32) ([]*resource.Version, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResourceVersions", ctx, tc, pn, rCan, before, after, limit)
	ret0, _ := ret[0].([]*resource.Version)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListResourceVersions indicates an expected call of ListResourceVersions.
func (mr *ServiceMockRecorder) ListResourceVersions(ctx, tc, pn, rCan, before, after, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResourceVersions", reflect.TypeOf((*Service)(nil).ListResourceVersions), ctx, tc, pn, rCan, before, after, limit)
}

// ListTeams mocks base method.
func (m *Service) ListTeams(ctx context.Context, un string) ([]*team.WithMembers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTeams", ctx, un)
	ret0, _ := ret[0].([]*team.WithMembers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTeams indicates an expected call of ListTeams.
func (mr *ServiceMockRecorder) ListTeams(ctx, un any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTeams", reflect.TypeOf((*Service)(nil).ListTeams), ctx, un)
}

// ListTriggersAfter mocks base method.
func (m *Service) ListTriggersAfter(ctx context.Context, tc, name string, afterID uint32) ([]*trigger.Trigger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTriggersAfter", ctx, tc, name, afterID)
	ret0, _ := ret[0].([]*trigger.Trigger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTriggersAfter indicates an expected call of ListTriggersAfter.
func (mr *ServiceMockRecorder) ListTriggersAfter(ctx, tc, name, afterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTriggersAfter", reflect.TypeOf((*Service)(nil).ListTriggersAfter), ctx, tc, name, afterID)
}

// ListUsers mocks base method.
func (m *Service) ListUsers(ctx context.Context) ([]*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx)
	ret0, _ := ret[0].([]*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *ServiceMockRecorder) ListUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*Service)(nil).ListUsers), ctx)
}

// ListWorkers mocks base method.
func (m *Service) ListWorkers(ctx context.Context) ([]*wkr.Worker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWorkers", ctx)
	ret0, _ := ret[0].([]*wkr.Worker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWorkers indicates an expected call of ListWorkers.
func (mr *ServiceMockRecorder) ListWorkers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWorkers", reflect.TypeOf((*Service)(nil).ListWorkers), ctx)
}

// NotifySerialGroupPendingBuilds mocks base method.
func (m *Service) NotifySerialGroupPendingBuilds(ctx context.Context, tc, pn, jn string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifySerialGroupPendingBuilds", ctx, tc, pn, jn)
}

// NotifySerialGroupPendingBuilds indicates an expected call of NotifySerialGroupPendingBuilds.
func (mr *ServiceMockRecorder) NotifySerialGroupPendingBuilds(ctx, tc, pn, jn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifySerialGroupPendingBuilds", reflect.TypeOf((*Service)(nil).NotifySerialGroupPendingBuilds), ctx, tc, pn, jn)
}

// PauseJob mocks base method.
func (m *Service) PauseJob(ctx context.Context, tc, pCan, jn string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseJob", ctx, tc, pCan, jn)
	ret0, _ := ret[0].(error)
	return ret0
}

// PauseJob indicates an expected call of PauseJob.
func (mr *ServiceMockRecorder) PauseJob(ctx, tc, pCan, jn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseJob", reflect.TypeOf((*Service)(nil).PauseJob), ctx, tc, pCan, jn)
}

// PausePipeline mocks base method.
func (m *Service) PausePipeline(ctx context.Context, tc, pCan string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PausePipeline", ctx, tc, pCan)
	ret0, _ := ret[0].(error)
	return ret0
}

// PausePipeline indicates an expected call of PausePipeline.
func (mr *ServiceMockRecorder) PausePipeline(ctx, tc, pCan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PausePipeline", reflect.TypeOf((*Service)(nil).PausePipeline), ctx, tc, pCan)
}

// PinResourceVersion mocks base method.
func (m *Service) PinResourceVersion(ctx context.Context, tc, pn, rCan string, versionID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PinResourceVersion", ctx, tc, pn, rCan, versionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PinResourceVersion indicates an expected call of PinResourceVersion.
func (mr *ServiceMockRecorder) PinResourceVersion(ctx, tc, pn, rCan, versionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PinResourceVersion", reflect.TypeOf((*Service)(nil).PinResourceVersion), ctx, tc, pn, rCan, versionID)
}

// RefreshToken mocks base method.
func (m *Service) RefreshToken(ctx context.Context, un string) (*user.WithMemberships, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, un)
	ret0, _ := ret[0].(*user.WithMemberships)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *ServiceMockRecorder) RefreshToken(ctx, un any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*Service)(nil).RefreshToken), ctx, un)
}

// RegenerateWebhookToken mocks base method.
func (m *Service) RegenerateWebhookToken(ctx context.Context, tc, pn, rCan string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegenerateWebhookToken", ctx, tc, pn, rCan)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegenerateWebhookToken indicates an expected call of RegenerateWebhookToken.
func (mr *ServiceMockRecorder) RegenerateWebhookToken(ctx, tc, pn, rCan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegenerateWebhookToken", reflect.TypeOf((*Service)(nil).RegenerateWebhookToken), ctx, tc, pn, rCan)
}

// RejectBuild mocks base method.
func (m *Service) RejectBuild(ctx context.Context, tc, pc, jn, buildNumber, username, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectBuild", ctx, tc, pc, jn, buildNumber, username, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectBuild indicates an expected call of RejectBuild.
func (mr *ServiceMockRecorder) RejectBuild(ctx, tc, pc, jn, buildNumber, username, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectBuild", reflect.TypeOf((*Service)(nil).RejectBuild), ctx, tc, pc, jn, buildNumber, username, message)
}

// RetryJobBuild mocks base method.
func (m *Service) RetryJobBuild(ctx context.Context, tc, pn, jn, buildNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryJobBuild", ctx, tc, pn, jn, buildNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryJobBuild indicates an expected call of RetryJobBuild.
func (mr *ServiceMockRecorder) RetryJobBuild(ctx, tc, pn, jn, buildNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryJobBuild", reflect.TypeOf((*Service)(nil).RetryJobBuild), ctx, tc, pn, jn, buildNumber)
}

// SetPipelinePublic mocks base method.
func (m *Service) SetPipelinePublic(ctx context.Context, tc, pn string, public bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPipelinePublic", ctx, tc, pn, public)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPipelinePublic indicates an expected call of SetPipelinePublic.
func (mr *ServiceMockRecorder) SetPipelinePublic(ctx, tc, pn, public any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPipelinePublic", reflect.TypeOf((*Service)(nil).SetPipelinePublic), ctx, tc, pn, public)
}

// StartPendingBuild mocks base method.
func (m *Service) StartPendingBuild(ctx context.Context, tc, pn, jn string, buildID uint32) (*build.Build, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartPendingBuild", ctx, tc, pn, jn, buildID)
	ret0, _ := ret[0].(*build.Build)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartPendingBuild indicates an expected call of StartPendingBuild.
func (mr *ServiceMockRecorder) StartPendingBuild(ctx, tc, pn, jn, buildID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartPendingBuild", reflect.TypeOf((*Service)(nil).StartPendingBuild), ctx, tc, pn, jn, buildID)
}

// TriggerPipelineJob mocks base method.
func (m *Service) TriggerPipelineJob(ctx context.Context, tc, pn, jn string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerPipelineJob", ctx, tc, pn, jn)
	ret0, _ := ret[0].(error)
	return ret0
}

// TriggerPipelineJob indicates an expected call of TriggerPipelineJob.
func (mr *ServiceMockRecorder) TriggerPipelineJob(ctx, tc, pn, jn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerPipelineJob", reflect.TypeOf((*Service)(nil).TriggerPipelineJob), ctx, tc, pn, jn)
}

// TriggerPipelineResource mocks base method.
func (m *Service) TriggerPipelineResource(ctx context.Context, tc, pn, rCan string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerPipelineResource", ctx, tc, pn, rCan)
	ret0, _ := ret[0].(error)
	return ret0
}

// TriggerPipelineResource indicates an expected call of TriggerPipelineResource.
func (mr *ServiceMockRecorder) TriggerPipelineResource(ctx, tc, pn, rCan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerPipelineResource", reflect.TypeOf((*Service)(nil).TriggerPipelineResource), ctx, tc, pn, rCan)
}

// TriggerResourceVersion mocks base method.
func (m *Service) TriggerResourceVersion(ctx context.Context, tc, pn, rCan string, versionID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerResourceVersion", ctx, tc, pn, rCan, versionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TriggerResourceVersion indicates an expected call of TriggerResourceVersion.
func (mr *ServiceMockRecorder) TriggerResourceVersion(ctx, tc, pn, rCan, versionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerResourceVersion", reflect.TypeOf((*Service)(nil).TriggerResourceVersion), ctx, tc, pn, rCan, versionID)
}

// UnpauseJob mocks base method.
func (m *Service) UnpauseJob(ctx context.Context, tc, pCan, jn string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpauseJob", ctx, tc, pCan, jn)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnpauseJob indicates an expected call of UnpauseJob.
func (mr *ServiceMockRecorder) UnpauseJob(ctx, tc, pCan, jn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpauseJob", reflect.TypeOf((*Service)(nil).UnpauseJob), ctx, tc, pCan, jn)
}

// UnpausePipeline mocks base method.
func (m *Service) UnpausePipeline(ctx context.Context, tc, pCan string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpausePipeline", ctx, tc, pCan)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnpausePipeline indicates an expected call of UnpausePipeline.
func (mr *ServiceMockRecorder) UnpausePipeline(ctx, tc, pCan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpausePipeline", reflect.TypeOf((*Service)(nil).UnpausePipeline), ctx, tc, pCan)
}

// UnpinResourceVersion mocks base method.
func (m *Service) UnpinResourceVersion(ctx context.Context, tc, pn, rCan string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpinResourceVersion", ctx, tc, pn, rCan)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnpinResourceVersion indicates an expected call of UnpinResourceVersion.
func (mr *ServiceMockRecorder) UnpinResourceVersion(ctx, tc, pn, rCan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpinResourceVersion", reflect.TypeOf((*Service)(nil).UnpinResourceVersion), ctx, tc, pn, rCan)
}

// UpdateApiTokenLastUsed mocks base method.
func (m *Service) UpdateApiTokenLastUsed(ctx context.Context, tokenID uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateApiTokenLastUsed", ctx, tokenID)
}

// UpdateApiTokenLastUsed indicates an expected call of UpdateApiTokenLastUsed.
func (mr *ServiceMockRecorder) UpdateApiTokenLastUsed(ctx, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateApiTokenLastUsed", reflect.TypeOf((*Service)(nil).UpdateApiTokenLastUsed), ctx, tokenID)
}

// UpdateJobBuild mocks base method.
func (m *Service) UpdateJobBuild(ctx context.Context, tc, pn, jn, buildNumber string, b build.Build) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJobBuild", ctx, tc, pn, jn, buildNumber, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateJobBuild indicates an expected call of UpdateJobBuild.
func (mr *ServiceMockRecorder) UpdateJobBuild(ctx, tc, pn, jn, buildNumber, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJobBuild", reflect.TypeOf((*Service)(nil).UpdateJobBuild), ctx, tc, pn, jn, buildNumber, b)
}

// UpdatePipeline mocks base method.
func (m *Service) UpdatePipeline(ctx context.Context, tc, pCan string, pp []byte, vars map[string]any, newName ...string) (*pipeline.Pipeline, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, tc, pCan, pp, vars}
	for _, a := range newName {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdatePipeline", varargs...)
	ret0, _ := ret[0].(*pipeline.Pipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePipeline indicates an expected call of UpdatePipeline.
func (mr *ServiceMockRecorder) UpdatePipeline(ctx, tc, pCan, pp, vars any, newName ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, tc, pCan, pp, vars}, newName...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePipeline", reflect.TypeOf((*Service)(nil).UpdatePipeline), varargs...)
}

// UpdatePipelineResource mocks base method.
func (m *Service) UpdatePipelineResource(ctx context.Context, tc, pn, rCan string, r resource.Resource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePipelineResource", ctx, tc, pn, rCan, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePipelineResource indicates an expected call of UpdatePipelineResource.
func (mr *ServiceMockRecorder) UpdatePipelineResource(ctx, tc, pn, rCan, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePipelineResource", reflect.TypeOf((*Service)(nil).UpdatePipelineResource), ctx, tc, pn, rCan, r)
}

// UpdateProfile mocks base method.
func (m *Service) UpdateProfile(ctx context.Context, un, fullName, newUsername string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, un, fullName, newUsername)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *ServiceMockRecorder) UpdateProfile(ctx, un, fullName, newUsername any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*Service)(nil).UpdateProfile), ctx, un, fullName, newUsername)
}

// UpdateTeam mocks base method.
func (m *Service) UpdateTeam(ctx context.Context, tc string, t team.Team) (*team.WithMembers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeam", ctx, tc, t)
	ret0, _ := ret[0].(*team.WithMembers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTeam indicates an expected call of UpdateTeam.
func (mr *ServiceMockRecorder) UpdateTeam(ctx, tc, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeam", reflect.TypeOf((*Service)(nil).UpdateTeam), ctx, tc, t)
}

// UpdateTeamMember mocks base method.
func (m *Service) UpdateTeamMember(ctx context.Context, tc, mc string, tm team.Member) (*team.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeamMember", ctx, tc, mc, tm)
	ret0, _ := ret[0].(*team.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTeamMember indicates an expected call of UpdateTeamMember.
func (mr *ServiceMockRecorder) UpdateTeamMember(ctx, tc, mc, tm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeamMember", reflect.TypeOf((*Service)(nil).UpdateTeamMember), ctx, tc, mc, tm)
}

// UpdateUser mocks base method.
func (m *Service) UpdateUser(ctx context.Context, un string, u user.User, isHash bool) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, un, u, isHash)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *ServiceMockRecorder) UpdateUser(ctx, un, u, isHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*Service)(nil).UpdateUser), ctx, un, u, isHash)
}

// UserLogin mocks base method.
func (m *Service) UserLogin(ctx context.Context, un, pass string) (*user.WithMemberships, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserLogin", ctx, un, pass)
	ret0, _ := ret[0].(*user.WithMemberships)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UserLogin indicates an expected call of UserLogin.
func (mr *ServiceMockRecorder) UserLogin(ctx, un, pass any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserLogin", reflect.TypeOf((*Service)(nil).UserLogin), ctx, un, pass)
}

// WebhookTrigger mocks base method.
func (m *Service) WebhookTrigger(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebhookTrigger", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// WebhookTrigger indicates an expected call of WebhookTrigger.
func (mr *ServiceMockRecorder) WebhookTrigger(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebhookTrigger", reflect.TypeOf((*Service)(nil).WebhookTrigger), ctx, token)
}

// WorkerHeartbeat mocks base method.
func (m *Service) WorkerHeartbeat(ctx context.Context, w wkr.Worker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkerHeartbeat", ctx, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// WorkerHeartbeat indicates an expected call of WorkerHeartbeat.
func (mr *ServiceMockRecorder) WorkerHeartbeat(ctx, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkerHeartbeat", reflect.TypeOf((*Service)(nil).WorkerHeartbeat), ctx, w)
}

// WorkersHealth mocks base method.
func (m *Service) WorkersHealth(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkersHealth", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkersHealth indicates an expected call of WorkersHealth.
func (mr *ServiceMockRecorder) WorkersHealth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkersHealth", reflect.TypeOf((*Service)(nil).WorkersHealth), ctx)
}
