// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xescugc/pikoci/pikoci/trigger (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/trigger_repository.go -mock_names=Repository=TriggerRepository -package mock github.com/xescugc/pikoci/pikoci/trigger Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	trigger "github.com/xescugc/pikoci/pikoci/trigger"
	gomock "go.uber.org/mock/gomock"
)

// TriggerRepository is a mock of Repository interface.
type TriggerRepository struct {
	ctrl     *gomock.Controller
	recorder *TriggerRepositoryMockRecorder
	isgomock struct{}
}

// TriggerRepositoryMockRecorder is the mock recorder for TriggerRepository.
type TriggerRepositoryMockRecorder struct {
	mock *TriggerRepository
}

// NewTriggerRepository creates a new mock instance.
func NewTriggerRepository(ctrl *gomock.Controller) *TriggerRepository {
	mock := &TriggerRepository{ctrl: ctrl}
	mock.recorder = &TriggerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *TriggerRepository) EXPECT() *TriggerRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *TriggerRepository) Create(ctx context.Context, tc, name string, version map[string]any) (*trigger.Trigger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tc, name, version)
	ret0, _ := ret[0].(*trigger.Trigger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *TriggerRepositoryMockRecorder) Create(ctx, tc, name, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*TriggerRepository)(nil).Create), ctx, tc, name, version)
}

// FilterAfter mocks base method.
func (m *TriggerRepository) FilterAfter(ctx context.Context, tc, name string, afterID uint32) ([]*trigger.Trigger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterAfter", ctx, tc, name, afterID)
	ret0, _ := ret[0].([]*trigger.Trigger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterAfter indicates an expected call of FilterAfter.
func (mr *TriggerRepositoryMockRecorder) FilterAfter(ctx, tc, name, afterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterAfter", reflect.TypeOf((*TriggerRepository)(nil).FilterAfter), ctx, tc, name, afterID)
}
