// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pikoci/pikoci/pikoci/wkr (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/worker_repository.go -mock_names=Repository=WorkerRepository -package mock github.com/pikoci/pikoci/pikoci/wkr Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	wkr "github.com/pikoci/pikoci/pikoci/wkr"
	gomock "go.uber.org/mock/gomock"
)

// WorkerRepository is a mock of Repository interface.
type WorkerRepository struct {
	ctrl     *gomock.Controller
	recorder *WorkerRepositoryMockRecorder
	isgomock struct{}
}

// WorkerRepositoryMockRecorder is the mock recorder for WorkerRepository.
type WorkerRepositoryMockRecorder struct {
	mock *WorkerRepository
}

// NewWorkerRepository creates a new mock instance.
func NewWorkerRepository(ctrl *gomock.Controller) *WorkerRepository {
	mock := &WorkerRepository{ctrl: ctrl}
	mock.recorder = &WorkerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *WorkerRepository) EXPECT() *WorkerRepositoryMockRecorder {
	return m.recorder
}

// DeleteBefore mocks base method.
func (m *WorkerRepository) DeleteBefore(ctx context.Context, before time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBefore", ctx, before)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBefore indicates an expected call of DeleteBefore.
func (mr *WorkerRepositoryMockRecorder) DeleteBefore(ctx, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBefore", reflect.TypeOf((*WorkerRepository)(nil).DeleteBefore), ctx, before)
}

// DeleteByName mocks base method.
func (m *WorkerRepository) DeleteByName(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByName", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByName indicates an expected call of DeleteByName.
func (mr *WorkerRepositoryMockRecorder) DeleteByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByName", reflect.TypeOf((*WorkerRepository)(nil).DeleteByName), ctx, name)
}

// Filter mocks base method.
func (m *WorkerRepository) Filter(ctx context.Context) ([]*wkr.Worker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx)
	ret0, _ := ret[0].([]*wkr.Worker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *WorkerRepositoryMockRecorder) Filter(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*WorkerRepository)(nil).Filter), ctx)
}

// Upsert mocks base method.
func (m *WorkerRepository) Upsert(ctx context.Context, w wkr.Worker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, w)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *WorkerRepositoryMockRecorder) Upsert(ctx, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*WorkerRepository)(nil).Upsert), ctx, w)
}
