services:
  pikoci:
    image: golang:1.25.1
    ports:
      - '4000:4000'
    volumes:
      - ..:/go/src/pikoci
      - $GOPATH/pkg/mod:/go/pkg/mod
      - $GOCACHE:/root/.cache/go-build
    working_dir: /go/src/pikoci
    environment:
      - PORT=4000
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root123
      - DB_NAME=qid_develop
      - DB_SYSTEM=sqlite
      - DB_FILE=pikoci.db

  worker:
    image: golang:1.25.1
    volumes:
      - ..:/go/src/pikoci
      - $GOPATH/pkg/mod:/go/pkg/mod
      - $GOCACHE:/root/.cache/go-build
    working_dir: /go/src/pikoci
    environment:
      - PIKOCI_URL=pikoci:4000

  mariadb:
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root123
    volumes:
      - ./data/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  postgresql:
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres123

  vault:
    ports:
      - '8200:8200'
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=test-root-token
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - SKIP_SETCAP=1
    cap_add:
      - IPC_LOCK
