// Code generated by "enumer -type=RouteName -transform=snake -output=route_names_string.go"; DO NOT EDIT.

package http

import (
	"fmt"
	"strings"
)

const _RouteNameName = "user_loginrefresh_tokencreate_userlist_usersget_userupdate_userdelete_userchange_passwordupdate_profilecreate_teamlist_teamsget_teamupdate_teamdelete_teamcreate_team_memberupdate_team_memberdelete_team_membercreate_pipelineupdate_pipelineget_pipelinedelete_pipelinelist_pipelinesget_pipeline_imagecreate_pipeline_imagetrigger_pipeline_joblist_pipeline_jobsget_pipeline_jobcreate_job_buildcreate_retry_job_buildupdate_job_builddelete_job_buildlist_job_buildsinsert_build_get_versionfind_build_get_versionsget_job_buildcancel_job_buildretry_job_buildstart_pending_buildfind_oldest_pending_buildnotify_serial_group_pending_buildsevaluate_downstream_jobslist_pipeline_resourcesget_pipeline_resourceupdate_pipeline_resourcetrigger_pipeline_resourcecreate_resource_versionlist_resource_versionspin_resource_versionunpin_resource_versiontrigger_resource_versionfire_trigger_notificationsget_resource_version_pathwebhook_triggerregenerate_webhook_tokencreate_triggerlist_triggers_afterexport_databasepause_pipelineunpause_pipelinepause_jobunpause_jobget_versionget_healthworker_heartbeatlist_workersworkers_healthdelete_workercreate_api_tokenlist_api_tokensdelete_api_tokenlist_audit_logget_build_reportapprove_buildreject_buildmark_build_as_warninggenerate_team_worker_tokenget_team_worker_tokenget_auth_methodso_auth_starto_auth_callbacko_auth_complete_profilelist_o_auth_providerscreate_o_auth_providerupdate_o_auth_providerdelete_o_auth_providerget_admin_auth_settingsupdate_admin_auth_settingslist_linked_accountsunlink_account"

var _RouteNameIndex = [...]uint16{0, 10, 23, 34, 44, 52, 63, 74, 89, 103, 114, 124, 132, 143, 154, 172, 190, 208, 223, 238, 250, 265, 279, 297, 318, 338, 356, 372, 388, 410, 426, 442, 457, 481, 504, 517, 533, 548, 567, 592, 626, 650, 673, 694, 718, 743, 766, 788, 808, 830, 854, 880, 905, 920, 944, 958, 977, 992, 1006, 1022, 1031, 1042, 1053, 1063, 1079, 1091, 1105, 1118, 1134, 1149, 1165, 1179, 1195, 1208, 1220, 1241, 1267, 1288, 1304, 1316, 1331, 1354, 1375, 1397, 1419, 1441, 1464, 1490, 1510, 1524}

const _RouteNameLowerName = "user_loginrefresh_tokencreate_userlist_usersget_userupdate_userdelete_userchange_passwordupdate_profilecreate_teamlist_teamsget_teamupdate_teamdelete_teamcreate_team_memberupdate_team_memberdelete_team_membercreate_pipelineupdate_pipelineget_pipelinedelete_pipelinelist_pipelinesget_pipeline_imagecreate_pipeline_imagetrigger_pipeline_joblist_pipeline_jobsget_pipeline_jobcreate_job_buildcreate_retry_job_buildupdate_job_builddelete_job_buildlist_job_buildsinsert_build_get_versionfind_build_get_versionsget_job_buildcancel_job_buildretry_job_buildstart_pending_buildfind_oldest_pending_buildnotify_serial_group_pending_buildsevaluate_downstream_jobslist_pipeline_resourcesget_pipeline_resourceupdate_pipeline_resourcetrigger_pipeline_resourcecreate_resource_versionlist_resource_versionspin_resource_versionunpin_resource_versiontrigger_resource_versionfire_trigger_notificationsget_resource_version_pathwebhook_triggerregenerate_webhook_tokencreate_triggerlist_triggers_afterexport_databasepause_pipelineunpause_pipelinepause_jobunpause_jobget_versionget_healthworker_heartbeatlist_workersworkers_healthdelete_workercreate_api_tokenlist_api_tokensdelete_api_tokenlist_audit_logget_build_reportapprove_buildreject_buildmark_build_as_warninggenerate_team_worker_tokenget_team_worker_tokenget_auth_methodso_auth_starto_auth_callbacko_auth_complete_profilelist_o_auth_providerscreate_o_auth_providerupdate_o_auth_providerdelete_o_auth_providerget_admin_auth_settingsupdate_admin_auth_settingslist_linked_accountsunlink_account"

func (i RouteName) String() string {
	if i < 0 || i >= RouteName(len(_RouteNameIndex)-1) {
		return fmt.Sprintf("RouteName(%d)", i)
	}
	return _RouteNameName[_RouteNameIndex[i]:_RouteNameIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RouteNameNoOp() {
	var x [1]struct{}
	_ = x[UserLogin-(0)]
	_ = x[RefreshToken-(1)]
	_ = x[CreateUser-(2)]
	_ = x[ListUsers-(3)]
	_ = x[GetUser-(4)]
	_ = x[UpdateUser-(5)]
	_ = x[DeleteUser-(6)]
	_ = x[ChangePassword-(7)]
	_ = x[UpdateProfile-(8)]
	_ = x[CreateTeam-(9)]
	_ = x[ListTeams-(10)]
	_ = x[GetTeam-(11)]
	_ = x[UpdateTeam-(12)]
	_ = x[DeleteTeam-(13)]
	_ = x[CreateTeamMember-(14)]
	_ = x[UpdateTeamMember-(15)]
	_ = x[DeleteTeamMember-(16)]
	_ = x[CreatePipeline-(17)]
	_ = x[UpdatePipeline-(18)]
	_ = x[GetPipeline-(19)]
	_ = x[DeletePipeline-(20)]
	_ = x[ListPipelines-(21)]
	_ = x[GetPipelineImage-(22)]
	_ = x[CreatePipelineImage-(23)]
	_ = x[TriggerPipelineJob-(24)]
	_ = x[ListPipelineJobs-(25)]
	_ = x[GetPipelineJob-(26)]
	_ = x[CreateJobBuild-(27)]
	_ = x[CreateRetryJobBuild-(28)]
	_ = x[UpdateJobBuild-(29)]
	_ = x[DeleteJobBuild-(30)]
	_ = x[ListJobBuilds-(31)]
	_ = x[InsertBuildGetVersion-(32)]
	_ = x[FindBuildGetVersions-(33)]
	_ = x[GetJobBuild-(34)]
	_ = x[CancelJobBuild-(35)]
	_ = x[RetryJobBuild-(36)]
	_ = x[StartPendingBuild-(37)]
	_ = x[FindOldestPendingBuild-(38)]
	_ = x[NotifySerialGroupPendingBuilds-(39)]
	_ = x[EvaluateDownstreamJobs-(40)]
	_ = x[ListPipelineResources-(41)]
	_ = x[GetPipelineResource-(42)]
	_ = x[UpdatePipelineResource-(43)]
	_ = x[TriggerPipelineResource-(44)]
	_ = x[CreateResourceVersion-(45)]
	_ = x[ListResourceVersions-(46)]
	_ = x[PinResourceVersion-(47)]
	_ = x[UnpinResourceVersion-(48)]
	_ = x[TriggerResourceVersion-(49)]
	_ = x[FireTriggerNotifications-(50)]
	_ = x[GetResourceVersionPath-(51)]
	_ = x[WebhookTrigger-(52)]
	_ = x[RegenerateWebhookToken-(53)]
	_ = x[CreateTrigger-(54)]
	_ = x[ListTriggersAfter-(55)]
	_ = x[ExportDatabase-(56)]
	_ = x[PausePipeline-(57)]
	_ = x[UnpausePipeline-(58)]
	_ = x[PauseJob-(59)]
	_ = x[UnpauseJob-(60)]
	_ = x[GetVersion-(61)]
	_ = x[GetHealth-(62)]
	_ = x[WorkerHeartbeat-(63)]
	_ = x[ListWorkers-(64)]
	_ = x[WorkersHealth-(65)]
	_ = x[DeleteWorker-(66)]
	_ = x[CreateApiToken-(67)]
	_ = x[ListApiTokens-(68)]
	_ = x[DeleteApiToken-(69)]
	_ = x[ListAuditLog-(70)]
	_ = x[GetBuildReport-(71)]
	_ = x[ApproveBuild-(72)]
	_ = x[RejectBuild-(73)]
	_ = x[MarkBuildAsWarning-(74)]
	_ = x[GenerateTeamWorkerToken-(75)]
	_ = x[GetTeamWorkerToken-(76)]
	_ = x[GetAuthMethods-(77)]
	_ = x[OAuthStart-(78)]
	_ = x[OAuthCallback-(79)]
	_ = x[OAuthCompleteProfile-(80)]
	_ = x[ListOAuthProviders-(81)]
	_ = x[CreateOAuthProvider-(82)]
	_ = x[UpdateOAuthProvider-(83)]
	_ = x[DeleteOAuthProvider-(84)]
	_ = x[GetAdminAuthSettings-(85)]
	_ = x[UpdateAdminAuthSettings-(86)]
	_ = x[ListLinkedAccounts-(87)]
	_ = x[UnlinkAccount-(88)]
}

var _RouteNameValues = []RouteName{UserLogin, RefreshToken, CreateUser, ListUsers, GetUser, UpdateUser, DeleteUser, ChangePassword, UpdateProfile, CreateTeam, ListTeams, GetTeam, UpdateTeam, DeleteTeam, CreateTeamMember, UpdateTeamMember, DeleteTeamMember, CreatePipeline, UpdatePipeline, GetPipeline, DeletePipeline, ListPipelines, GetPipelineImage, CreatePipelineImage, TriggerPipelineJob, ListPipelineJobs, GetPipelineJob, CreateJobBuild, CreateRetryJobBuild, UpdateJobBuild, DeleteJobBuild, ListJobBuilds, InsertBuildGetVersion, FindBuildGetVersions, GetJobBuild, CancelJobBuild, RetryJobBuild, StartPendingBuild, FindOldestPendingBuild, NotifySerialGroupPendingBuilds, EvaluateDownstreamJobs, ListPipelineResources, GetPipelineResource, UpdatePipelineResource, TriggerPipelineResource, CreateResourceVersion, ListResourceVersions, PinResourceVersion, UnpinResourceVersion, TriggerResourceVersion, FireTriggerNotifications, GetResourceVersionPath, WebhookTrigger, RegenerateWebhookToken, CreateTrigger, ListTriggersAfter, ExportDatabase, PausePipeline, UnpausePipeline, PauseJob, UnpauseJob, GetVersion, GetHealth, WorkerHeartbeat, ListWorkers, WorkersHealth, DeleteWorker, CreateApiToken, ListApiTokens, DeleteApiToken, ListAuditLog, GetBuildReport, ApproveBuild, RejectBuild, MarkBuildAsWarning, GenerateTeamWorkerToken, GetTeamWorkerToken, GetAuthMethods, OAuthStart, OAuthCallback, OAuthCompleteProfile, ListOAuthProviders, CreateOAuthProvider, UpdateOAuthProvider, DeleteOAuthProvider, GetAdminAuthSettings, UpdateAdminAuthSettings, ListLinkedAccounts, UnlinkAccount}

var _RouteNameNameToValueMap = map[string]RouteName{
	_RouteNameName[0:10]:           UserLogin,
	_RouteNameLowerName[0:10]:      UserLogin,
	_RouteNameName[10:23]:          RefreshToken,
	_RouteNameLowerName[10:23]:     RefreshToken,
	_RouteNameName[23:34]:          CreateUser,
	_RouteNameLowerName[23:34]:     CreateUser,
	_RouteNameName[34:44]:          ListUsers,
	_RouteNameLowerName[34:44]:     ListUsers,
	_RouteNameName[44:52]:          GetUser,
	_RouteNameLowerName[44:52]:     GetUser,
	_RouteNameName[52:63]:          UpdateUser,
	_RouteNameLowerName[52:63]:     UpdateUser,
	_RouteNameName[63:74]:          DeleteUser,
	_RouteNameLowerName[63:74]:     DeleteUser,
	_RouteNameName[74:89]:          ChangePassword,
	_RouteNameLowerName[74:89]:     ChangePassword,
	_RouteNameName[89:103]:         UpdateProfile,
	_RouteNameLowerName[89:103]:    UpdateProfile,
	_RouteNameName[103:114]:        CreateTeam,
	_RouteNameLowerName[103:114]:   CreateTeam,
	_RouteNameName[114:124]:        ListTeams,
	_RouteNameLowerName[114:124]:   ListTeams,
	_RouteNameName[124:132]:        GetTeam,
	_RouteNameLowerName[124:132]:   GetTeam,
	_RouteNameName[132:143]:        UpdateTeam,
	_RouteNameLowerName[132:143]:   UpdateTeam,
	_RouteNameName[143:154]:        DeleteTeam,
	_RouteNameLowerName[143:154]:   DeleteTeam,
	_RouteNameName[154:172]:        CreateTeamMember,
	_RouteNameLowerName[154:172]:   CreateTeamMember,
	_RouteNameName[172:190]:        UpdateTeamMember,
	_RouteNameLowerName[172:190]:   UpdateTeamMember,
	_RouteNameName[190:208]:        DeleteTeamMember,
	_RouteNameLowerName[190:208]:   DeleteTeamMember,
	_RouteNameName[208:223]:        CreatePipeline,
	_RouteNameLowerName[208:223]:   CreatePipeline,
	_RouteNameName[223:238]:        UpdatePipeline,
	_RouteNameLowerName[223:238]:   UpdatePipeline,
	_RouteNameName[238:250]:        GetPipeline,
	_RouteNameLowerName[238:250]:   GetPipeline,
	_RouteNameName[250:265]:        DeletePipeline,
	_RouteNameLowerName[250:265]:   DeletePipeline,
	_RouteNameName[265:279]:        ListPipelines,
	_RouteNameLowerName[265:279]:   ListPipelines,
	_RouteNameName[279:297]:        GetPipelineImage,
	_RouteNameLowerName[279:297]:   GetPipelineImage,
	_RouteNameName[297:318]:        CreatePipelineImage,
	_RouteNameLowerName[297:318]:   CreatePipelineImage,
	_RouteNameName[318:338]:        TriggerPipelineJob,
	_RouteNameLowerName[318:338]:   TriggerPipelineJob,
	_RouteNameName[338:356]:        ListPipelineJobs,
	_RouteNameLowerName[338:356]:   ListPipelineJobs,
	_RouteNameName[356:372]:        GetPipelineJob,
	_RouteNameLowerName[356:372]:   GetPipelineJob,
	_RouteNameName[372:388]:        CreateJobBuild,
	_RouteNameLowerName[372:388]:   CreateJobBuild,
	_RouteNameName[388:410]:        CreateRetryJobBuild,
	_RouteNameLowerName[388:410]:   CreateRetryJobBuild,
	_RouteNameName[410:426]:        UpdateJobBuild,
	_RouteNameLowerName[410:426]:   UpdateJobBuild,
	_RouteNameName[426:442]:        DeleteJobBuild,
	_RouteNameLowerName[426:442]:   DeleteJobBuild,
	_RouteNameName[442:457]:        ListJobBuilds,
	_RouteNameLowerName[442:457]:   ListJobBuilds,
	_RouteNameName[457:481]:        InsertBuildGetVersion,
	_RouteNameLowerName[457:481]:   InsertBuildGetVersion,
	_RouteNameName[481:504]:        FindBuildGetVersions,
	_RouteNameLowerName[481:504]:   FindBuildGetVersions,
	_RouteNameName[504:517]:        GetJobBuild,
	_RouteNameLowerName[504:517]:   GetJobBuild,
	_RouteNameName[517:533]:        CancelJobBuild,
	_RouteNameLowerName[517:533]:   CancelJobBuild,
	_RouteNameName[533:548]:        RetryJobBuild,
	_RouteNameLowerName[533:548]:   RetryJobBuild,
	_RouteNameName[548:567]:        StartPendingBuild,
	_RouteNameLowerName[548:567]:   StartPendingBuild,
	_RouteNameName[567:592]:        FindOldestPendingBuild,
	_RouteNameLowerName[567:592]:   FindOldestPendingBuild,
	_RouteNameName[592:626]:        NotifySerialGroupPendingBuilds,
	_RouteNameLowerName[592:626]:   NotifySerialGroupPendingBuilds,
	_RouteNameName[626:650]:        EvaluateDownstreamJobs,
	_RouteNameLowerName[626:650]:   EvaluateDownstreamJobs,
	_RouteNameName[650:673]:        ListPipelineResources,
	_RouteNameLowerName[650:673]:   ListPipelineResources,
	_RouteNameName[673:694]:        GetPipelineResource,
	_RouteNameLowerName[673:694]:   GetPipelineResource,
	_RouteNameName[694:718]:        UpdatePipelineResource,
	_RouteNameLowerName[694:718]:   UpdatePipelineResource,
	_RouteNameName[718:743]:        TriggerPipelineResource,
	_RouteNameLowerName[718:743]:   TriggerPipelineResource,
	_RouteNameName[743:766]:        CreateResourceVersion,
	_RouteNameLowerName[743:766]:   CreateResourceVersion,
	_RouteNameName[766:788]:        ListResourceVersions,
	_RouteNameLowerName[766:788]:   ListResourceVersions,
	_RouteNameName[788:808]:        PinResourceVersion,
	_RouteNameLowerName[788:808]:   PinResourceVersion,
	_RouteNameName[808:830]:        UnpinResourceVersion,
	_RouteNameLowerName[808:830]:   UnpinResourceVersion,
	_RouteNameName[830:854]:        TriggerResourceVersion,
	_RouteNameLowerName[830:854]:   TriggerResourceVersion,
	_RouteNameName[854:880]:        FireTriggerNotifications,
	_RouteNameLowerName[854:880]:   FireTriggerNotifications,
	_RouteNameName[880:905]:        GetResourceVersionPath,
	_RouteNameLowerName[880:905]:   GetResourceVersionPath,
	_RouteNameName[905:920]:        WebhookTrigger,
	_RouteNameLowerName[905:920]:   WebhookTrigger,
	_RouteNameName[920:944]:        RegenerateWebhookToken,
	_RouteNameLowerName[920:944]:   RegenerateWebhookToken,
	_RouteNameName[944:958]:        CreateTrigger,
	_RouteNameLowerName[944:958]:   CreateTrigger,
	_RouteNameName[958:977]:        ListTriggersAfter,
	_RouteNameLowerName[958:977]:   ListTriggersAfter,
	_RouteNameName[977:992]:        ExportDatabase,
	_RouteNameLowerName[977:992]:   ExportDatabase,
	_RouteNameName[992:1006]:       PausePipeline,
	_RouteNameLowerName[992:1006]:  PausePipeline,
	_RouteNameName[1006:1022]:      UnpausePipeline,
	_RouteNameLowerName[1006:1022]: UnpausePipeline,
	_RouteNameName[1022:1031]:      PauseJob,
	_RouteNameLowerName[1022:1031]: PauseJob,
	_RouteNameName[1031:1042]:      UnpauseJob,
	_RouteNameLowerName[1031:1042]: UnpauseJob,
	_RouteNameName[1042:1053]:      GetVersion,
	_RouteNameLowerName[1042:1053]: GetVersion,
	_RouteNameName[1053:1063]:      GetHealth,
	_RouteNameLowerName[1053:1063]: GetHealth,
	_RouteNameName[1063:1079]:      WorkerHeartbeat,
	_RouteNameLowerName[1063:1079]: WorkerHeartbeat,
	_RouteNameName[1079:1091]:      ListWorkers,
	_RouteNameLowerName[1079:1091]: ListWorkers,
	_RouteNameName[1091:1105]:      WorkersHealth,
	_RouteNameLowerName[1091:1105]: WorkersHealth,
	_RouteNameName[1105:1118]:      DeleteWorker,
	_RouteNameLowerName[1105:1118]: DeleteWorker,
	_RouteNameName[1118:1134]:      CreateApiToken,
	_RouteNameLowerName[1118:1134]: CreateApiToken,
	_RouteNameName[1134:1149]:      ListApiTokens,
	_RouteNameLowerName[1134:1149]: ListApiTokens,
	_RouteNameName[1149:1165]:      DeleteApiToken,
	_RouteNameLowerName[1149:1165]: DeleteApiToken,
	_RouteNameName[1165:1179]:      ListAuditLog,
	_RouteNameLowerName[1165:1179]: ListAuditLog,
	_RouteNameName[1179:1195]:      GetBuildReport,
	_RouteNameLowerName[1179:1195]: GetBuildReport,
	_RouteNameName[1195:1208]:      ApproveBuild,
	_RouteNameLowerName[1195:1208]: ApproveBuild,
	_RouteNameName[1208:1220]:      RejectBuild,
	_RouteNameLowerName[1208:1220]: RejectBuild,
	_RouteNameName[1220:1241]:      MarkBuildAsWarning,
	_RouteNameLowerName[1220:1241]: MarkBuildAsWarning,
	_RouteNameName[1241:1267]:      GenerateTeamWorkerToken,
	_RouteNameLowerName[1241:1267]: GenerateTeamWorkerToken,
	_RouteNameName[1267:1288]:      GetTeamWorkerToken,
	_RouteNameLowerName[1267:1288]: GetTeamWorkerToken,
	_RouteNameName[1288:1304]:      GetAuthMethods,
	_RouteNameLowerName[1288:1304]: GetAuthMethods,
	_RouteNameName[1304:1316]:      OAuthStart,
	_RouteNameLowerName[1304:1316]: OAuthStart,
	_RouteNameName[1316:1331]:      OAuthCallback,
	_RouteNameLowerName[1316:1331]: OAuthCallback,
	_RouteNameName[1331:1354]:      OAuthCompleteProfile,
	_RouteNameLowerName[1331:1354]: OAuthCompleteProfile,
	_RouteNameName[1354:1375]:      ListOAuthProviders,
	_RouteNameLowerName[1354:1375]: ListOAuthProviders,
	_RouteNameName[1375:1397]:      CreateOAuthProvider,
	_RouteNameLowerName[1375:1397]: CreateOAuthProvider,
	_RouteNameName[1397:1419]:      UpdateOAuthProvider,
	_RouteNameLowerName[1397:1419]: UpdateOAuthProvider,
	_RouteNameName[1419:1441]:      DeleteOAuthProvider,
	_RouteNameLowerName[1419:1441]: DeleteOAuthProvider,
	_RouteNameName[1441:1464]:      GetAdminAuthSettings,
	_RouteNameLowerName[1441:1464]: GetAdminAuthSettings,
	_RouteNameName[1464:1490]:      UpdateAdminAuthSettings,
	_RouteNameLowerName[1464:1490]: UpdateAdminAuthSettings,
	_RouteNameName[1490:1510]:      ListLinkedAccounts,
	_RouteNameLowerName[1490:1510]: ListLinkedAccounts,
	_RouteNameName[1510:1524]:      UnlinkAccount,
	_RouteNameLowerName[1510:1524]: UnlinkAccount,
}

var _RouteNameNames = []string{
	_RouteNameName[0:10],
	_RouteNameName[10:23],
	_RouteNameName[23:34],
	_RouteNameName[34:44],
	_RouteNameName[44:52],
	_RouteNameName[52:63],
	_RouteNameName[63:74],
	_RouteNameName[74:89],
	_RouteNameName[89:103],
	_RouteNameName[103:114],
	_RouteNameName[114:124],
	_RouteNameName[124:132],
	_RouteNameName[132:143],
	_RouteNameName[143:154],
	_RouteNameName[154:172],
	_RouteNameName[172:190],
	_RouteNameName[190:208],
	_RouteNameName[208:223],
	_RouteNameName[223:238],
	_RouteNameName[238:250],
	_RouteNameName[250:265],
	_RouteNameName[265:279],
	_RouteNameName[279:297],
	_RouteNameName[297:318],
	_RouteNameName[318:338],
	_RouteNameName[338:356],
	_RouteNameName[356:372],
	_RouteNameName[372:388],
	_RouteNameName[388:410],
	_RouteNameName[410:426],
	_RouteNameName[426:442],
	_RouteNameName[442:457],
	_RouteNameName[457:481],
	_RouteNameName[481:504],
	_RouteNameName[504:517],
	_RouteNameName[517:533],
	_RouteNameName[533:548],
	_RouteNameName[548:567],
	_RouteNameName[567:592],
	_RouteNameName[592:626],
	_RouteNameName[626:650],
	_RouteNameName[650:673],
	_RouteNameName[673:694],
	_RouteNameName[694:718],
	_RouteNameName[718:743],
	_RouteNameName[743:766],
	_RouteNameName[766:788],
	_RouteNameName[788:808],
	_RouteNameName[808:830],
	_RouteNameName[830:854],
	_RouteNameName[854:880],
	_RouteNameName[880:905],
	_RouteNameName[905:920],
	_RouteNameName[920:944],
	_RouteNameName[944:958],
	_RouteNameName[958:977],
	_RouteNameName[977:992],
	_RouteNameName[992:1006],
	_RouteNameName[1006:1022],
	_RouteNameName[1022:1031],
	_RouteNameName[1031:1042],
	_RouteNameName[1042:1053],
	_RouteNameName[1053:1063],
	_RouteNameName[1063:1079],
	_RouteNameName[1079:1091],
	_RouteNameName[1091:1105],
	_RouteNameName[1105:1118],
	_RouteNameName[1118:1134],
	_RouteNameName[1134:1149],
	_RouteNameName[1149:1165],
	_RouteNameName[1165:1179],
	_RouteNameName[1179:1195],
	_RouteNameName[1195:1208],
	_RouteNameName[1208:1220],
	_RouteNameName[1220:1241],
	_RouteNameName[1241:1267],
	_RouteNameName[1267:1288],
	_RouteNameName[1288:1304],
	_RouteNameName[1304:1316],
	_RouteNameName[1316:1331],
	_RouteNameName[1331:1354],
	_RouteNameName[1354:1375],
	_RouteNameName[1375:1397],
	_RouteNameName[1397:1419],
	_RouteNameName[1419:1441],
	_RouteNameName[1441:1464],
	_RouteNameName[1464:1490],
	_RouteNameName[1490:1510],
	_RouteNameName[1510:1524],
}

// RouteNameString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RouteNameString(s string) (RouteName, error) {
	if val, ok := _RouteNameNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RouteNameNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to RouteName values", s)
}

// RouteNameValues returns all values of the enum
func RouteNameValues() []RouteName {
	return _RouteNameValues
}

// RouteNameStrings returns a slice of all String values of the enum
func RouteNameStrings() []string {
	strs := make([]string, len(_RouteNameNames))
	copy(strs, _RouteNameNames)
	return strs
}

// IsARouteName returns "true" if the value is listed in the enum definition. "false" otherwise
func (i RouteName) IsARouteName() bool {
	for _, v := range _RouteNameValues {
		if i == v {
			return true
		}
	}
	return false
}
